before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq firefox
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
addons:
  apt:
    packages:
      - build-essential
      - gettext
      - python-dev
      - zlib1g-dev
      - libpq-dev
      - xvfb
      - xserver-xorg
      - firefox
      - iceweasel
      - libtiff4-dev
      - libjpeg8-dev
      - libfreetype6-dev
      - liblcms1-dev
      - libwebp-dev
      - graphviz-dev
      - python-setuptools
      - python3-dev
      - python-virtualenv
      - python-pip
      - automake
      - libtool
      - libreadline6
      - libreadline6-dev
      - libreadline-dev
      - libsqlite3-dev
      - libxml2
      - libxml2-dev
      - libssl-dev
      - libbz2-dev
      - wget
      - curl
      - llvm
  firefox: "latest"
  postgresql: "9.3"
  xserver-xorg: "latest"
language: python
python:
  - "2.7"
install:
  - "pip install hitch"
  - "cd tests"
  - "hitch init"
script:
  - "hitch test . --extra '{\"xvfb\":true, \"pause_on_failure\":false}'"
